# -*- coding: utf-8 -*-
"""Impact Hub (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zOrGmarO9xB6eWGM0n176Ftk_Xy8mME7
"""

# Install and import required libraries
!pip install requests joblib nbformat --quiet

import pandas as pd
import numpy as np
import requests
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

print("✅ Libraries imported")

# List of 47 Kenyan counties
counties = [
 'Mombasa','Kwale','Kilifi','Tana River','Lamu','Taita-Taveta','Garissa','Wajir','Mandera',
 'Marsabit','Isiolo','Meru','Tharaka-Nithi','Embu','Kitui','Machakos','Makueni','Nyandarua',
 'Nyeri','Kirinyaga','Muranga','Kiambu','Turkana','West Pokot','Samburu','Trans Nzoia',
 'Uasin Gishu','Elgeyo-Marakwet','Nandi','Baringo','Laikipia','Nakuru','Narok','Kajiado',
 'Kericho','Bomet','Kakamega','Vihiga','Bungoma','Busia','Siaya','Kisumu','Homa Bay',
 'Migori','Kisii','Nyamira','Nairobi'
]
len(counties)

# Create synthetic dataset for training
np.random.seed(42)
n = 600
data = {
    'county': np.random.choice(counties, n),
    'rainfall': np.random.uniform(40, 300, n),   # mm
    'temperature': np.random.uniform(12, 34, n), # °C
    'humidity': np.random.uniform(30, 95, n),    # %
    'soil_ph': np.random.uniform(4.5, 8.0, n),
    'month': np.random.choice(range(1,13), n)
}
df = pd.DataFrame(data)

# Synthetic label
df['planting_ready'] = np.where(
    (df['rainfall'] > 100) & (df['rainfall'] < 250) &
    (df['temperature'] > 18) & (df['temperature'] < 28) &
    (df['soil_ph'] > 5.5) & (df['soil_ph'] < 7.5), 1, 0
)

df['planting_ready'].value_counts(normalize=True)

# One-hot encoding
df_encoded = pd.get_dummies(df, columns=['county','month'], drop_first=True)
X = df_encoded.drop('planting_ready', axis=1)
y = df_encoded['planting_ready']

# Train-test split and training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=150, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Save model for use in Streamlit or local app later
joblib.dump(model, "AgriIntel_Model.joblib")
print("Model saved as AgriIntel_Model.joblib")

# --- Set your OpenWeather API key here ---
API_KEY = "09d2cdb6020a0ed1f7d8cbe3a82c3e14"  # <-- Paste your OpenWeather API key as a string

# Optional mapping: override county -> city if needed (leave empty to use county name)
county_to_city = {
    # Example: 'Nairobi': 'Nairobi', 'Mombasa': 'Mombasa'
}

def fetch_weather_for_city(city_name):
    '''Return (rainfall_mm, temp_c, humidity_pct) or None on failure.'''
    try:
        url = f"http://api.openweathermap.org/data/2.5/weather?q={city_name},KE&appid={API_KEY}&units=metric"
        resp = requests.get(url, timeout=10)
        if resp.status_code != 200:
            return None
        data = resp.json()
        # rainfall in last 1h if available, else 0; OpenWeather uses 'rain' field
        rainfall = data.get('rain', {}).get('1h', 0.0)
        temp = data['main']['temp']
        humidity = data['main'].get('humidity', np.nan)
        return float(rainfall), float(temp), float(humidity)
    except Exception as e:
        return None

# Test fetch (will need API_KEY filled to succeed)
# fetch_weather_for_city("Nakuru")

# Build a DataFrame with live/simulated weather for all counties and predict
results = []
current_month = pd.Timestamp.now().month

for county in counties:
    city = county_to_city.get(county, county)  # use mapping or county name
    weather = None
    if API_KEY:
        weather = fetch_weather_for_city(city)
    if weather is None:
        # fallback simulated values (still realistic ranges)
        rainfall = np.random.uniform(20, 220)    # mm
        temp = np.random.uniform(14, 32)         # °C
        humidity = np.random.uniform(30, 95)     # %
    else:
        rainfall, temp, humidity = weather

    soil_ph = np.random.uniform(5.0, 7.8)  # soil pH simulated for now
    month = current_month

    # Prepare input row for model (ensure all model features exist)
    row = {
        'rainfall': rainfall,
        'temperature': temp,
        'soil_ph': soil_ph,
    }
    # county one-hot features
    for c in counties:
        row[f'county_{c}'] = 1 if c == county else 0
    # month one-hot features (model used months 2..12 after drop_first)
    for m in range(2,13):
        row[f'month_{m}'] = 1 if m == month else 0

    # Ensure columns order matches model
    for col in X.columns:
        if col not in row:
            row[col] = 0
    input_df = pd.DataFrame([row])[X.columns]

    pred = model.predict(input_df)[0]
    results.append({
        'county': county,
        'month': month,
        'temperature_C': round(temp,2),
        'rainfall_mm': round(rainfall,2),
        'humidity_pct': round(humidity,2),
        'soil_ph': round(soil_ph,2),
        'planting_ready': int(pred)
    })

results_df = pd.DataFrame(results)
results_df.head(10)
# Convert numeric prediction (0/1) into human-readable label
results_df['Planting_Condition'] = results_df['planting_ready'].apply(
    lambda x: "✅ Ideal" if x == 1 else "❌ Not Ideal"
)

# Clean up units for readability
results_df['Temperature'] = results_df['temperature_C'].astype(str) + " °C"
results_df['Rainfall'] = results_df['rainfall_mm'].astype(str) + " mm"
results_df['Humidity'] = results_df['humidity_pct'].astype(str) + " %"

# Select only the main columns for display
pretty_df = results_df[['county', 'month', 'Temperature', 'Rainfall', 'Humidity', 'Planting_Condition']]
pretty_df.head(10)

# Save to CSV
results_df.to_csv("AgriIntel_Kenya_county_predictions.csv", index=False)
print("Saved results to AgriIntel_Kenya_county_predictions.csv")

# Display summary table and basic plots
display(results_df)

# Readiness counts
print("\nReadiness counts:\n", results_df['planting_ready'].value_counts())

# Plot readiness by county (sorted)
plt.figure(figsize=(12,6))
s = results_df.sort_values('planting_ready', ascending=False)
sns.barplot(x='county', y='planting_ready', data=s)
plt.xticks(rotation=90)
plt.ylabel("Planting readiness (1 = ideal)")
plt.title("Planting Readiness by County")
plt.show()

# Download link in Colab UI
from google.colab import files
files.download("AgriIntel_Kenya_county_predictions.csv")